package ast;

public enum KindExp {
  OR, AND, IGUAL, DISTINTO, MENORIGUAL, MAYORIGUAL, MENOR, MAYOR,
  SUMA, RESTA, MULT, DIV, MOD, POS, NEG, NOT, REF, VALOR,
  NEW, READ, CORCHETE, PUNTO, FLECHA, FUNCION, PARENTESIS,
  ENTERO, BOOLEANO, NULL, IDEN
}
