
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Mar 31 10:14:10 CEST 2024
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int FIDELSECASTRO = 14;
  public static final int RESTO = 28;
  public static final int DISTINTO = 50;
  public static final int CONST = 22;
  public static final int PUNTOYCOMA = 46;
  public static final int LLCIERRA = 45;
  public static final int CCIERRA = 39;
  public static final int PCIERRA = 43;
  public static final int CABRE = 38;
  public static final int ASTERISCO = 26;
  public static final int REF = 37;
  public static final int DELETE = 21;
  public static final int WRITE = 18;
  public static final int RED = 17;
  public static final int MENORIGUAL = 30;
  public static final int AND = 34;
  public static final int IGUAL = 29;
  public static final int FUN = 12;
  public static final int TYPE = 51;
  public static final int OR = 35;
  public static final int BOOL = 3;
  public static final int CALL = 19;
  public static final int DIV = 27;
  public static final int TROTSKIF = 13;
  public static final int MAIN = 8;
  public static final int USSWHILE = 15;
  public static final int MAYORIGUAL = 31;
  public static final int EOF = 0;
  public static final int RETURN = 48;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int MENOS = 25;
  public static final int NULL = 11;
  public static final int LENINT = 9;
  public static final int MENOR = 32;
  public static final int VOID = 52;
  public static final int BOOLSHEVIK = 10;
  public static final int ASIGNACION = 47;
  public static final int PABRE = 42;
  public static final int MAYOR = 33;
  public static final int GUEVARRAY = 5;
  public static final int FLECHA = 41;
  public static final int NEG = 36;
  public static final int FORLETARIAT = 16;
  public static final int PUNTO = 40;
  public static final int IDEN = 23;
  public static final int ENTPOS = 4;
  public static final int STALINTRUCT = 7;
  public static final int POINTER = 6;
  public static final int VAR = 2;
  public static final int LLABRE = 44;
  public static final int MAS = 24;
}

